import type { Metadata } from "next";
import Header from "@/component/header/Header";
import Sidebar from "@/component/sidebar/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div className="relative flex min-h-screen bg-gray-50 overflow-visible">
          <Sidebar />
          <div className="relative flex-1 flex flex-col w-full ml-60">
            <Header />
            <main className="sticky top-0 z-5 flex-1 p-6 w-full">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
